### ISSUE TITLE
Undocumented roadmap

### ISSUE THREAD

**Issue by DurandA** [nRFCloud/api#7]
It is not clear what features will be included in this API when it will be complete.

Will it provides all features available in the [nRF Cloud dashboard](https://nrfcloud.com/#/dashboard)? Does it inclute the WebSocket API?

**Comment by coderbyheart** [comment]
Please understand that we are not publishing our roadmap. You will learn about the availability and scope of new features on [nrfcloud.com](https://nrfcloud.com/).

**Comment by coderbyheart** [comment]
P.S.: we would like to hear what you are planning, if you are interested in participating in preview releases, please reach out to us via the Feedback button on nrfcloud.com
